version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-service

  node-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-service
    env_file:
      - variables.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb
    env_file:
      - variables.env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure this line is correctly pointing to your init.sql file
    ports:
      - "3306:3306"

volumes:
  db_data:
